### ISSUE TITLE
try to uniformly use colors

### ISSUE THREAD

**Issue by aric87** [mse2321/basketball-quiz#11]
If you're going to use a bunch of pre-defined colors (blue, green, white etc) then you should stick to that. You have some that are keywords, then you use #000 and #fff. Change those to black and white to maintain that consistency. 
https://github.com/mse2321/basketball-quiz/blob/master/css/style.css#L187
https://github.com/mse2321/basketball-quiz/blob/master/css/style.css#L169

**Comment by mse2321** [comment]
Done
